/* LINE Stamp Project model。Static v2とPhase 1 v1の後方互換を提供します。 */
(function(root,factory){const api=factory();if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.LineStampCore=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const LIMITS=Object.freeze({maxFileBytes:1048576,common:Object.freeze({maxFileBytes:1048576,maxZipBytes:62914560,colorMode:'RGB',transparentBackground:true}),mainImage:Object.freeze({width:240,height:240}),tabImage:Object.freeze({width:96,height:74,format:'PNG'}),static:Object.freeze({counts:Object.freeze([8,16,24,32,40]),mainFormat:'PNG',stickerFormat:'PNG',stickerMaxWidth:370,stickerMaxHeight:320,sticker:Object.freeze({format:'PNG',maxWidth:370,maxHeight:320,dimensionMultiple:2,minDpi:72,recommendedOuterMarginPx:10})}),animated:Object.freeze({counts:Object.freeze([8,16,24]),mainFormat:'APNG',stickerFormat:'APNG',stickerMaxWidth:320,stickerMaxHeight:270,framesMin:5,framesMax:20,loopsMin:1,loopsMax:4,totalDurationMax:4,allowedDurations:Object.freeze([1,2,3,4]),sticker:Object.freeze({format:'APNG',maxWidth:320,maxHeight:270,minEitherDimension:270,sameFrameDimensions:true,framesMin:5,framesMax:20,loopsMin:1,loopsMax:4,allowedDurations:Object.freeze([1,2,3,4]),totalDurationMax:4,removeFrameMargins:true,removeStaticParts:true,firstFrameUsedAsStill:true})})});
const STICKER_SLOT_POLICY=Object.freeze({strategy:'explicit-slot',field:'slot',firstSlot:1}),DEFAULT_EDIT=Object.freeze({threshold:1,margin:10,upscale:true,scale:1,offsetX:0,offsetY:0}),DEFAULT_SPECIAL=Object.freeze({sourceStickerId:null,upscale:true,scale:1,offsetX:0,offsetY:0});
function constraints(type){if(type!=='static'&&type!=='animated')throw new Error('LINE Project typeはstaticまたはanimatedです。');return LIMITS[type];}
function createProject(type='static',targetStickerCount){const rule=constraints(type),count=targetStickerCount??rule.counts[0];if(!rule.counts.includes(count))throw new Error(`${type}では${count}個を選択できません。`);return{format:'line-stamp-project',version:2,type,targetStickerCount:count,mainImage:{...DEFAULT_SPECIAL},tabImage:{...DEFAULT_SPECIAL},stickers:[]};}
function normalizeStickerCount(type,currentCount){const counts=constraints(type).counts,available=counts.filter(n=>n<=currentCount);return available.length?available.at(-1):counts[0];}
function stickerSlotNumbers(count){if(!Number.isSafeInteger(count)||count<1)throw new Error('スタンプ予定数が不正です。');return Array.from({length:count},(_,i)=>i+1);}
const clone=value=>JSON.parse(JSON.stringify(value));
function validateSpecial(value,label){if(!value||typeof value!=='object'||Array.isArray(value))throw new Error(`${label}設定が不正です。`);const out={...DEFAULT_SPECIAL,...value};if(out.sourceStickerId!==null&&(typeof out.sourceStickerId!=='string'||!out.sourceStickerId))throw new Error(`${label}参照が不正です。`);if(typeof out.upscale!=='boolean'||!Number.isFinite(out.scale)||out.scale<.1||out.scale>4)throw new Error(`${label}倍率が不正です。`);for(const k of['offsetX','offsetY'])if(!Number.isSafeInteger(out[k])||Math.abs(out[k])>1000)throw new Error(`${label} offsetが不正です。`);return out;}
function validateEdit(value){if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Sticker編集値が不正です。');const out={...DEFAULT_EDIT,...value};if(!Number.isSafeInteger(out.threshold)||out.threshold<0||out.threshold>254||!Number.isSafeInteger(out.margin)||out.margin<0||out.margin>40||typeof out.upscale!=='boolean'||!Number.isFinite(out.scale)||out.scale<.1||out.scale>4)throw new Error('Sticker trim / fit設定が不正です。');for(const k of['offsetX','offsetY'])if(!Number.isSafeInteger(out[k])||Math.abs(out[k])>1000)throw new Error('Sticker offsetが不正です。');return out;}
function validateSticker(value,count,ids,slots){if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('StickerがObjectではありません。');if(typeof value.id!=='string'||!/^[A-Za-z0-9_-]{1,80}$/.test(value.id)||ids.has(value.id))throw new Error('Sticker IDが不正または重複しています。');if(!Number.isSafeInteger(value.slot)||value.slot<1||value.slot>count||slots.has(value.slot))throw new Error('Sticker slotが不正または重複しています。');const s=value.source;if(!s||typeof s!=='object'||typeof s.name!=='string'||!s.name||s.name.length>255||!['image/png','image/webp','image/jpeg'].includes(s.type)||!Number.isSafeInteger(s.width)||s.width<1||s.width>16384||!Number.isSafeInteger(s.height)||s.height<1||s.height>16384||s.width*s.height>33554432||typeof s.data!=='string'||!new RegExp(`^data:${s.type.replace('/','\\/')};base64,`,'i').test(s.data))throw new Error('Sticker元画像が不正です。');ids.add(value.id);slots.add(value.slot);return{id:value.id,slot:value.slot,source:{name:s.name,type:s.type,width:s.width,height:s.height,data:s.data},edit:validateEdit(value.edit)};}
function validateProject(value){if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('LINE ProjectがObjectではありません。');if(value.format!=='line-stamp-project')throw new Error('未対応のLINE Project形式です。');if(value.version===1){const rule=constraints(value.type);if(!Number.isSafeInteger(value.targetStickerCount)||!rule.counts.includes(value.targetStickerCount)||value.mainImage!==null||value.tabImage!==null||!Array.isArray(value.stickers)||value.stickers.length)throw new Error('LINE Project v1が不正です。');return createProject(value.type,value.targetStickerCount);}if(value.version!==2)throw new Error('未対応のLINE Project versionです。');const rule=constraints(value.type);if(!Number.isSafeInteger(value.targetStickerCount)||!rule.counts.includes(value.targetStickerCount))throw new Error('スタンプ予定数がtypeの制約と一致しません。');if(!Array.isArray(value.stickers)||value.stickers.length>value.targetStickerCount)throw new Error('Sticker配列が不正です。');if(value.type==='animated'&&value.stickers.length)throw new Error('Animated Sticker画像は未対応です。');const ids=new Set(),slots=new Set(),stickers=value.stickers.map(s=>validateSticker(s,value.targetStickerCount,ids,slots)).sort((a,b)=>a.slot-b.slot);if(stickers.reduce((n,s)=>n+s.source.width*s.source.height,0)>100663296)throw new Error('元画像の合計画素数が上限を超えます。');const mainImage=validateSpecial(value.mainImage,'Main'),tabImage=validateSpecial(value.tabImage,'Tab');for(const ref of[mainImage.sourceStickerId,tabImage.sourceStickerId])if(ref!==null&&!ids.has(ref))throw new Error('Main / Tabの参照先Stickerがありません。');return{format:'line-stamp-project',version:2,type:value.type,targetStickerCount:value.targetStickerCount,mainImage,tabImage,stickers};}
function changeType(project,type){constraints(type);if(!project||typeof project!=='object'||Array.isArray(project))throw new Error('LINE ProjectがObjectではありません。');return{...project,type,targetStickerCount:normalizeStickerCount(type,project.targetStickerCount)};}
function bySlot(project,slot){return project.stickers.find(s=>s.slot===slot)||null;}
function removeSticker(project,slot){const target=bySlot(project,slot);if(!target)return project;const clear=x=>x.sourceStickerId===target.id?{...x,sourceStickerId:null}:x;return{...project,stickers:project.stickers.filter(s=>s!==target),mainImage:clear(project.mainImage),tabImage:clear(project.tabImage)};}
function putSticker(project,sticker){const clean=clone(sticker),existing=bySlot(project,clean.slot);if(existing)return{...project,stickers:project.stickers.map(s=>s===existing?clean:s).sort((a,b)=>a.slot-b.slot)};return{...project,stickers:[...project.stickers,clean].sort((a,b)=>a.slot-b.slot)};}
function moveSticker(project,from,to){if(!Number.isSafeInteger(from)||!Number.isSafeInteger(to)||to<1||to>project.targetStickerCount)return project;const a=bySlot(project,from),b=bySlot(project,to);if(!a)return project;return{...project,stickers:project.stickers.map(s=>s===a?{...s,slot:to}:s===b?{...s,slot:from}:s).sort((x,y)=>x.slot-y.slot)};}
function outputNames(count){return['main.png','tab.png',...stickerSlotNumbers(count).map(n=>String(n).padStart(2,'0')+'.png')];}
function validateCompletion(project,files=[]){const errors=[];if(project.type!=='static')errors.push('Animated Sticker / APNG対応は開発中です。');for(const n of stickerSlotNumbers(project.targetStickerCount))if(!bySlot(project,n))errors.push(`${String(n).padStart(2,'0')}.png のStickerが未設定です。`);if(!project.mainImage.sourceStickerId)errors.push('Main Imageが未設定です。');if(!project.tabImage.sourceStickerId)errors.push('Tab Imageが未設定です。');let total=0;for(const f of files){const size=f.data?.length??f.size??0;total+=size;if(size>LIMITS.maxFileBytes)errors.push(`${f.name} が1MBを超えています。`);}if(total>LIMITS.common.maxZipBytes)errors.push('PNG合計が60MBを超えています。');return errors;}
return{LIMITS,STICKER_SLOT_POLICY,DEFAULT_EDIT,DEFAULT_SPECIAL,constraints,createProject,validateProject,normalizeStickerCount,stickerSlotNumbers,changeType,bySlot,putSticker,removeSticker,moveSticker,outputNames,validateCompletion};});
