/* LINE Static Sticker Phase 2。file://・offline・外部依存なし。 */
(function(){
'use strict';
const C=window.LineStampCore,I=window.LineImageCore,R=window.LineRenderer,Z=window.ZipWriter,W=window.WorkspaceShell,$=id=>document.getElementById(id);
const offsetYToUi=value=>value===0?0:-value,offsetYFromUi=value=>value===0?0:-value;
let project=C.createProject(),runtime=new Map(),selectedSlot=1,projectUrl=null,saveLinkUsed=false,busy=false,downloadUrls=[];
function notice(text,kind='info'){$('lineNotice').textContent=text;$('lineNotice').className=`notice ${kind}`;$('lineNotice').hidden=!text;}
function revokeProject(){if(projectUrl)URL.revokeObjectURL(projectUrl);projectUrl=null;saveLinkUsed=false;$('lineSaveProject').hidden=true;$('lineSaveProject').removeAttribute('href');$('lineConfirmSave').hidden=true;$('lineConfirmSave').disabled=true;}
function revokeDownloads(){for(const url of downloadUrls)URL.revokeObjectURL(url);downloadUrls=[];$('lineDownloads').replaceChildren();$('lineDownloads').hidden=true;}
function invalidate(text='未保存の変更があります。Projectをもう一度用意してください。'){revokeProject();revokeDownloads();$('lineProjectStatus').textContent=text;$('lineOutputStatus').textContent='編集内容が変わりました。PNG / ZIPをもう一度用意してください。';}
function changed(){invalidate();W.setDirty('line',true);return render();}
function itemAt(slot){const model=C.bySlot(project,slot);return model?{...model,...runtime.get(model.id)}:null;}
function itemById(id){const model=project.stickers.find(s=>s.id===id);return model?{...model,...runtime.get(id)}:null;}
function setBusy(value){busy=value;for(const control of document.querySelectorAll('#lineWorkspace button,#lineWorkspace input,#lineWorkspace select')){if(value){control.dataset.lineBusyDisabled=control.disabled?'1':'0';control.disabled=true;}else{control.disabled=control.dataset.lineBusyDisabled==='1';delete control.dataset.lineBusyDisabled;}}}
function fileDataUrl(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('画像ファイルを読めません。'));reader.readAsDataURL(file);});}
function blobFromDataUrl(data){const [head,body]=data.split(','),type=/^data:([^;]+);base64$/i.exec(head)?.[1];if(!type||!body)throw new Error('埋め込み画像形式が不正です。');const raw=atob(body),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return new Blob([bytes],{type});}
async function decode(source){const blob=blobFromDataUrl(source.data),image=await createImageBitmap(blob);try{if(image.width!==source.width||image.height!==source.height)throw new Error('保存寸法と画像寸法が一致しません。');if(image.width*image.height>33554432)throw new Error('元画像の画素数が上限を超えます。');const canvas=document.createElement('canvas');canvas.width=image.width;canvas.height=image.height;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(image,0,0);const rgba=ctx.getImageData(0,0,image.width,image.height).data;return{image,rgba,bounds:null};}catch(error){image.close();throw error;}}
async function modelFromFile(file,slot,keepId){if(!['image/png','image/webp','image/jpeg'].includes(file.type))throw new Error(`${file.name}: PNG / WebP / JPEGのみ対応です。`);const data=await fileDataUrl(file),probe=await createImageBitmap(file);const source={name:file.name,type:file.type,width:probe.width,height:probe.height,data};probe.close();const model={id:keepId||((crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`).replace(/[^A-Za-z0-9_-]/g,'')),slot,source,edit:{...C.DEFAULT_EDIT}},decoded=await decode(source);decoded.bounds=I.alphaBounds(decoded.rgba,source.width,source.height,model.edit.threshold);if(!decoded.bounds){decoded.image.close();throw new Error(`${file.name}: 完全透明のため追加できません。`);}return{model,decoded};}
function refreshBounds(model){const rt=runtime.get(model.id);rt.bounds=I.alphaBounds(rt.rgba,model.source.width,model.source.height,model.edit.threshold);}
function closeRuntime(map=runtime){for(const value of map.values())value.image?.close();map.clear();}
function renderCanvas(canvas,item,kind='sticker',edit,plan){if(!item){canvas.width=canvas.height=1;return null;}return kind==='sticker'?R.sticker(canvas,item,plan):R.special(canvas,item,kind==='main'?240:96,kind==='main'?240:74,edit,plan);}
function specialStatus(kind){const config=project[kind==='main'?'mainImage':'tabImage'],item=itemById(config.sourceStickerId);return item?`${String(item.slot).padStart(2,'0')} ${item.source.name}`:'未設定';}
function analyzeProject(){const errors=[],stickerPlans=new Map(),specialPlans={};for(const model of project.stickers){const rt=runtime.get(model.id);try{stickerPlans.set(model.id,I.stickerPlan(rt?.bounds,model.edit));}catch(error){errors.push(`${String(model.slot).padStart(2,'0')}.png: ${error.message}`);}}for(const [kind,key,width,height,label] of [['main','mainImage',240,240,'Main Image'],['tab','tabImage',96,74,'Tab Image']]){const config=project[key],item=itemById(config.sourceStickerId);if(!item)continue;try{specialPlans[kind]=I.fixedPlan(item.bounds,width,height,config,label);}catch(error){errors.push(error.message);}}return{errors,stickerPlans,specialPlans};}
function render(){const rule=C.constraints(project.type),animated=project.type==='animated';$('lineType').value=project.type;$('lineStickerCount').replaceChildren(...rule.counts.map(n=>{const o=document.createElement('option');o.value=n;o.textContent=`${n}個`;o.selected=n===project.targetStickerCount;return o;}));$('lineMainSpec').textContent=`240 × 240 px · ${rule.mainFormat} · 1MB以下`;$('lineStickerSpec').textContent=`最大 ${rule.stickerMaxWidth} × ${rule.stickerMaxHeight} px · ${rule.stickerFormat} · 1個1MB以下`;$('lineAnimationSpec').hidden=!animated;$('lineApngStatus').hidden=!animated;$('lineStaticTools').hidden=animated;$('linePrepareOutput').disabled=busy||animated;
  $('lineSlots').replaceChildren(...C.stickerSlotNumbers(project.targetStickerCount).map(slot=>{const model=C.bySlot(project,slot),node=document.createElement('button');node.type='button';node.className=`line-slot${model?' filled':''}${slot===selectedSlot?' selected':''}`;node.dataset.slot=slot;const n=document.createElement('span');n.textContent=String(slot).padStart(2,'0');node.append(n);if(model){const img=document.createElement('img');img.src=model.source.data;img.alt='';node.append(img);const small=document.createElement('small');small.textContent=model.source.name;node.append(small);}else{const strong=document.createElement('strong');strong.textContent='空き';node.append(strong);const small=document.createElement('small');small.textContent='画像を追加';node.append(small);}node.onclick=()=>{selectedSlot=slot;render();};return node;}));
  const analysis=analyzeProject(),renderErrors=[...analysis.errors],selected=itemAt(selectedSlot),show=!!selected&&!animated;$('lineInspectorEmpty').hidden=show;$('lineInspectorContent').hidden=!show;if(show){const plan=analysis.stickerPlans.get(selected.id);if(plan)try{renderCanvas($('linePreviewCanvas'),selected,'sticker',selected.edit,plan);$('linePreviewInfo').textContent=`${selected.source.name} · 元 ${selected.source.width}×${selected.source.height} → PNG ${plan.width}×${plan.height}`;}catch(error){renderErrors.push(`Preview: ${error.message}`);}else $('linePreviewInfo').textContent=analysis.errors.find(x=>x.startsWith(`${String(selected.slot).padStart(2,'0')}.png:`))||'Previewを描画できません。';for(const [id,key] of[['lineThreshold','threshold'],['lineMargin','margin'],['lineScale','scale'],['lineOffsetX','offsetX'],['lineOffsetY','offsetY']])$(id).value=key==='offsetY'?offsetYToUi(selected.edit[key]):selected.edit[key];$('lineUpscale').checked=selected.edit.upscale;$('lineMoveUp').disabled=selectedSlot<=1;$('lineMoveDown').disabled=selectedSlot>=project.targetStickerCount;$('lineDownloadSelected').disabled=busy||!plan;}
  for(const [id,key] of[['lineMainOffsetX','offsetX'],['lineMainOffsetY','offsetY']])$(id).value=key==='offsetY'?offsetYToUi(project.mainImage[key]):project.mainImage[key];for(const [id,key] of[['lineTabOffsetX','offsetX'],['lineTabOffsetY','offsetY']])$(id).value=key==='offsetY'?offsetYToUi(project.tabImage[key]):project.tabImage[key];for(const [kind,key] of [['main','mainImage'],['tab','tabImage']]){const item=itemById(project[key].sourceStickerId),plan=analysis.specialPlans[kind];if(!item)renderCanvas($(kind==='main'?'lineMainCanvas':'lineTabCanvas'),null);else if(plan)try{renderCanvas($(kind==='main'?'lineMainCanvas':'lineTabCanvas'),item,kind,project[key],plan);}catch(error){renderErrors.push(`${kind==='main'?'Main Image':'Tab Image'}: ${error.message}`);}}$('lineMainStatus').textContent=specialStatus('main');$('lineTabStatus').textContent=specialStatus('tab');
  const errors=[...new Set(renderErrors),...C.validateCompletion(project)];$('linePrepareOutput').disabled=busy||animated||renderErrors.length>0;$('lineValidation').textContent=errors.length?errors.slice(0,6).join('\n')+(errors.length>6?`\nほか${errors.length-6}件`:''):'Static Sticker一式を出力できます。';$('lineValidation').className=`notice ${errors.length?'warning':'info'} spaced`;$('lineProjectSummary').textContent=`${animated?'Animated':'Static'} · ${project.targetStickerCount} stickers\nMain: ${specialStatus('main')}\nTab: ${specialStatus('tab')}\nSticker: ${project.stickers.length} / ${project.targetStickerCount}`;return renderErrors;
}
async function addFiles(files,replaceSlot=null){if(busy||project.type!=='static')return;const list=[...files];if(!list.length)return;setBusy(true);let added=0,failed=[];try{for(const file of list){let slot=replaceSlot;if(slot===null){const order=[selectedSlot,...C.stickerSlotNumbers(project.targetStickerCount).filter(n=>n!==selectedSlot)];slot=order.find(n=>!C.bySlot(project,n));}if(!slot){failed.push(`${file.name}: 空きスロットがありません。`);continue;}const old=C.bySlot(project,slot);try{const {model,decoded}=await modelFromFile(file,slot,old?.id);if(old)runtime.get(old.id)?.image.close();runtime.set(model.id,decoded);project=C.putSticker(project,model);selectedSlot=slot;added++;}catch(error){failed.push(error.message);}if(replaceSlot!==null)break;}}finally{setBusy(false);}if(added)changed();else render();notice(`${added}枚を追加しました。${failed.length?'\n'+failed.join('\n'):''}`,failed.length?'warning':'info');}
function editSelected(key,value){const model=C.bySlot(project,selectedSlot);if(!model)return;let candidate;try{candidate=C.validateEdit({...model.edit,[key]:value});}catch(error){render();notice(error.message,'error');return;}model.edit=candidate;refreshBounds(model);const errors=changed();notice(errors.length?errors[0]:'編集値を更新しました。',errors.length?'error':'info');}
function editSpecial(kind,key,value){let candidate;try{candidate=C.validateSpecial({...project[kind],[key]:value},kind==='mainImage'?'Main':'Tab');}catch(error){render();notice(error.message,'error');return;}project[kind]=candidate;const errors=changed();notice(errors.length?errors[0]:'編集値を更新しました。',errors.length?'error':'info');}
async function loadProject(file){if(!file||busy||!W.confirmDestructive('line'))return;setBusy(true);const candidate=new Map();try{let parsed;try{parsed=JSON.parse(await file.text());}catch{throw new Error('Project JSONを解析できません。');}const validated=C.validateProject(parsed);for(const model of validated.stickers){const rt=await decode(model.source);rt.bounds=I.alphaBounds(rt.rgba,model.source.width,model.source.height,model.edit.threshold);candidate.set(model.id,rt);}closeRuntime();runtime=candidate;project=validated;selectedSlot=1;invalidate('ProjectをLOADしました。');W.setDirty('line',false);notice(`${file.name}: ${project.type} / ${project.targetStickerCount}個のLINE Projectを読み込みました。`);}catch(error){closeRuntime(candidate);notice(`Projectを読み込めません：${error.message} 現在の編集内容は維持しました。`,'error');}finally{setBusy(false);render();}}
function prepareProject(){try{const snapshot=C.validateProject(project),blob=new Blob([JSON.stringify(snapshot,null,2)+'\n'],{type:'application/json'});revokeProject();projectUrl=URL.createObjectURL(blob);$('lineSaveProject').href=projectUrl;$('lineSaveProject').download=`line-stamp-${project.type}-${project.targetStickerCount}.line-project.json`;$('lineSaveProject').hidden=false;$('lineConfirmSave').hidden=false;$('lineConfirmSave').disabled=true;$('lineProjectStatus').textContent='Projectを用意済み。リンクを使用し、保存完了を確認してください。';notice('LINE Project v2を用意しました。元画像と編集値を保持しています。');}catch(error){notice(`Projectを用意できません：${error.message}`,'error');}}
async function buildFile(name,item,kind,edit){const canvas=document.createElement('canvas');const plan=renderCanvas(canvas,item,kind,edit),data=await R.pngBytes(canvas),dims=I.parsePng(data);if(dims.width!==plan.width||dims.height!==plan.height)throw new Error(`${name}のPNG寸法を確認できません。`);return{name,data};}
function addDownload(name,blob){const url=URL.createObjectURL(blob);downloadUrls.push(url);const a=document.createElement('a');a.className='button';a.href=url;a.download=name;a.textContent=name;$('lineDownloads').append(a);$('lineDownloads').hidden=false;}
async function prepareSelected(){const item=itemAt(selectedSlot);if(!item)return;setBusy(true);try{revokeDownloads();const file=await buildFile(`${String(selectedSlot).padStart(2,'0')}.png`,item,'sticker');addDownload(file.name,new Blob([file.data],{type:'image/png'}));notice(`${file.name}を用意しました。`);}catch(error){notice(error.message,'error');}finally{setBusy(false);render();}}
async function prepareOutput(){if(busy)return;setBusy(true);try{const initial=[...C.validateCompletion(project),...analyzeProject().errors];if(initial.length)throw new Error(initial.join('\n'));const files=[];files.push(await buildFile('main.png',itemById(project.mainImage.sourceStickerId),'main',project.mainImage));files.push(await buildFile('tab.png',itemById(project.tabImage.sourceStickerId),'tab',project.tabImage));for(const slot of C.stickerSlotNumbers(project.targetStickerCount))files.push(await buildFile(`${String(slot).padStart(2,'0')}.png`,itemAt(slot),'sticker'));const errors=C.validateCompletion(project,files);if(errors.length)throw new Error(errors.join('\n'));const zip=Z.create(files);if(zip.length>C.LIMITS.common.maxZipBytes)throw new Error('ZIPが60MBを超えています。');revokeDownloads();for(const file of files)addDownload(file.name,new Blob([file.data],{type:'image/png'}));addDownload('line-static-stickers.zip',new Blob([zip],{type:'application/zip'}));$('lineOutputStatus').textContent=`${files.length} PNG / ZIP ${(zip.length/1024).toFixed(1)}KB を用意しました。` ;notice('LINE Static Sticker一式を用意しました。Preview・個別PNG・ZIPは同じ描画経路です。');}catch(error){revokeDownloads();$('lineOutputStatus').textContent='出力できません。validationを確認してください。';notice(`PNG / ZIPを用意できません：\n${error.message}`,'error');}finally{setBusy(false);render();}}
$('lineType').addEventListener('change',event=>{const type=event.target.value;if(project.stickers.length&&!confirm('種類変更すると読み込んだStatic画像を削除します。続けますか？')){render();return;}closeRuntime();project=C.createProject(type,C.normalizeStickerCount(type,project.targetStickerCount));selectedSlot=1;changed();});
$('lineStickerCount').addEventListener('change',event=>{const count=Number(event.target.value),removed=project.stickers.filter(s=>s.slot>count);if(removed.length&&!confirm(`${removed.length}枚の範囲外Stickerを削除します。続けますか？`)){render();return;}for(const s of removed)runtime.get(s.id)?.image.close();const ids=new Set(removed.map(s=>s.id));project={...project,targetStickerCount:count,stickers:project.stickers.filter(s=>s.slot<=count),mainImage:ids.has(project.mainImage.sourceStickerId)?{...project.mainImage,sourceStickerId:null}:project.mainImage,tabImage:ids.has(project.tabImage.sourceStickerId)?{...project.tabImage,sourceStickerId:null}:project.tabImage};selectedSlot=Math.min(selectedSlot,count);changed();});
$('lineNewProject').onclick=()=>{if(!W.confirmDestructive('line'))return;closeRuntime();project=C.createProject();selectedSlot=1;invalidate('新しいLINE Projectです。');W.setDirty('line',false);notice('新しいLINE Projectを開始しました。');render();};
$('linePrepareProject').onclick=prepareProject;$('lineSaveProject').onclick=()=>{saveLinkUsed=true;$('lineConfirmSave').disabled=false;};$('lineConfirmSave').onclick=()=>{if(!saveLinkUsed)return;W.setDirty('line',false);$('lineProjectStatus').textContent='保存完了を確認しました。';$('lineConfirmSave').disabled=true;notice('LINE Projectの保存完了を記録しました。');};
$('lineLoadProject').onclick=()=>$('lineProjectInput').click();$('lineProjectInput').onchange=e=>{const f=e.target.files[0];e.target.value='';if(f)loadProject(f);};$('lineAddImages').onclick=()=>$('lineImageInput').click();$('lineImageInput').onchange=e=>{const files=[...e.target.files];e.target.value='';addFiles(files);};$('lineReplaceImage').onclick=()=>$('lineReplaceInput').click();$('lineReplaceInput').onchange=e=>{const files=[...e.target.files];e.target.value='';addFiles(files,selectedSlot);};
for(const [id,key,parse] of[['lineThreshold','threshold',Number],['lineMargin','margin',Number],['lineScale','scale',Number],['lineOffsetX','offsetX',Number],['lineOffsetY','offsetY',offsetYFromUi]])$(id).onchange=e=>editSelected(key,parse(e.target.value));$('lineUpscale').onchange=e=>editSelected('upscale',e.target.checked);
$('lineMoveUp').onclick=()=>{project=C.moveSticker(project,selectedSlot,selectedSlot-1);selectedSlot--;changed();};$('lineMoveDown').onclick=()=>{project=C.moveSticker(project,selectedSlot,selectedSlot+1);selectedSlot++;changed();};$('lineDeleteImage').onclick=()=>{const model=C.bySlot(project,selectedSlot);if(!model||!confirm(`${String(selectedSlot).padStart(2,'0')} を削除しますか？`))return;runtime.get(model.id)?.image.close();runtime.delete(model.id);project=C.removeSticker(project,selectedSlot);changed();};
$('lineUseMain').onclick=()=>{const model=C.bySlot(project,selectedSlot);if(model){project.mainImage={...project.mainImage,sourceStickerId:model.id};changed();}};$('lineUseTab').onclick=()=>{const model=C.bySlot(project,selectedSlot);if(model){project.tabImage={...project.tabImage,sourceStickerId:model.id};changed();}};
for(const [id,kind,key] of[['lineMainOffsetX','mainImage','offsetX'],['lineMainOffsetY','mainImage','offsetY'],['lineTabOffsetX','tabImage','offsetX'],['lineTabOffsetY','tabImage','offsetY']])$(id).onchange=e=>editSpecial(kind,key,key==='offsetY'?offsetYFromUi(Number(e.target.value)):Number(e.target.value));
$('lineDownloadSelected').onclick=prepareSelected;$('linePrepareOutput').onclick=prepareOutput;
document.addEventListener('dragover',e=>{if(W.state.active==='line'){e.preventDefault();$('lineWorkspace').classList.add('drag-over');}});document.addEventListener('dragleave',e=>{if(!e.relatedTarget)$('lineWorkspace').classList.remove('drag-over');});document.addEventListener('drop',e=>{if(W.state.active==='line'){e.preventDefault();$('lineWorkspace').classList.remove('drag-over');addFiles(e.dataTransfer.files);}});document.addEventListener('paste',e=>{if(W.state.active==='line'){const files=[...e.clipboardData.files].filter(f=>f.type.startsWith('image/'));if(files.length){e.preventDefault();addFiles(files);}}});
W.setUnsafeChecker('line',()=>busy);window.addEventListener('pagehide',event=>{if(!event.persisted){revokeProject();revokeDownloads();closeRuntime();}});render();
})();
